### ISSUE TITLE
Cannot find module 'superb'

### ISSUE THREAD

**Issue by pdehaan** [Kikobeats/finepack#1]
I tried installing **finepack** globally and running it on a local directory and got the following error:

> _Error: Cannot find module 'superb'_
### Steps to reproduce

``` sh
$ npm i finepack --global
/Users/pdehaan/.npm-packages/bin/finepack -> /Users/pdehaan/.npm-packages/lib/node_modules/finepack/bin/index.js
finepack@1.0.0 /Users/pdehaan/.npm-packages/lib/node_modules/finepack
├── sort-keys-recursive@1.0.2 (sort-keys@1.0.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.0, has-ansi@1.0.3, strip-ansi@2.0.1)
├── coffee-script@1.9.1
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.0, indent-string@1.2.1)
└── update-notifier@0.3.1 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.0, latest-version@1.0.0, configstore@0.3.2)


$ finepack

module.js:340
    throw err;
          ^
Error: Cannot find module 'superb'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/pdehaan/.npm-packages/lib/node_modules/finepack/lib/Finepack.coffee:7:21)
  at Object.<anonymous> (/Users/pdehaan/.npm-packages/lib/node_modules/finepack/lib/Finepack.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/pdehaan/.npm-packages/lib/node_modules/finepack/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/pdehaan/.npm-packages/lib/node_modules/finepack/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/pdehaan/.npm-packages/lib/node_modules/finepack/bin/index.js:6:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

I didn't see the **superb** dependency listed in [_./package.json_](https://github.com/Kikobeats/finepack/blob/4853cf1134cc3d63df715de4468f6ef7d5c4cf18/package.json#L14-L24), but I did notice a reference in the stack trace to a `require()` in [./lib/Finepack.coffee:7](https://github.com/Kikobeats/finepack/blob/4853cf1134cc3d63df715de4468f6ef7d5c4cf18/lib/Finepack.coffee#L7).

**Comment by pdehaan** [comment]
Probably not relevant, but I'm apparently running node 0.10.35 and npm 1.4.28 (via nvm):

``` sh
$ node -v; npm -v
v0.10.35
1.4.28
```

**Comment by Kikobeats** [comment]
oh, thanks for the issue. Actually the dependency is not used, I'm going to fix

**Comment by Kikobeats** [comment]
@pdehaan check now :)
